grafana:
  enabled: false
defaultRules:
  rules:
    alertmanager: false
    etcd: false
    kubePrometheusNodeAlerting: false
    kubeScheduler: false
alertmanager:
  enabled: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
prometheus:
  prometheusSpec:
    containers:
      - name: stackdriver-sidecar
        image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.9.0
        imagePullPolicy: Always
        args:
          - --stackdriver.project-id=helm-test-sidecar
          - --prometheus.wal-directory=/prometheus/wal
          - --stackdriver.kubernetes.location=us-central1
          - --stackdriver.kubernetes.cluster-name=cluster-3
        ports:
          - name: stackdriver
            containerPort: 9091
        volumeMounts:
          - name:    prometheus-prometheus-kube-prometheus-prometheus-db
            mountPath: /prometheus

  
